
--CAU 1

SELECT MASV, TENSV, CASE PHAI WHEN 1 THEN 'Nam' ELSE N'Nữ' END AS GIOITINH, 
NGAYSINH, DIACHI, DIENTHOAI, MALOP
FROM SINHVIEN
WHERE PHAI = 1 AND DIACHI LIKE N'%ĐÀ NẴNG'

--CAU2

--HIEN THI SINH VIEN THUOC LOP K19QTM

SELECT * FROM SINHVIEN
WHERE MALOP LIKE N'K19TPM'

--BAI 3
--HIEN THI THONG TIN BAO GOM MALOP, TENLOP, CVHT VA SISO

SELECT A.MALOP, TENLOP, CVHT , COUNT(MASV) AS SISO
FROM SINHVIEN A, LOP B
WHERE A.MALOP = B.MALOP
GROUP BY A.MALOP, TENLOP, CVHT

--BAI 4
--Hiển thị thông tin sinh viên gồm: Mã SV, tên SV, GT, ngày sinh, Điểm TB kiểm tra lần1

SELECT A.MASV, TENSV, CASE PHAI WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI, NGAYSINH, SUM(SOTC*DIEMLAN1)/SUM(SOTC) AS TBDIEMLAN1
FROM SINHVIEN A, DIEM B, MONHOC C
WHERE A.MASV = B.MASV
GROUP BY A.MASV, TENSV, PHAI, NGAYSINH

--BAI5
--Hiển thị thông tin sinh viên gồm: Mã SV, tên SV, GT, ngày sinh, Điểm TB kiểm tra
--lần1. Sắp xếp sinh viên theo thứ tự giảm dần của điểm tb

SELECT A.MASV, TENSV, PHAI, NGAYSINH, AVG(DIEMLAN1) AS TBDIEMLAN1
FROM SINHVIEN A, DIEM B
WHERE A.MASV = B.MASV
GROUP BY A.MASV, TENSV, PHAI, NGAYSINH
ORDER BY TBDIEMLAN1 DESC

--BAI6
--Hiển thị những người có điểm TB lần 1 lớn hơn 8.
SELECT A.MASV, TENSV, PHAI, NGAYSINH, AVG(DIEMLAN1) AS TBDIEMLAN1
FROM SINHVIEN A, DIEM B
WHERE A.MASV = B.MASV
GROUP BY A.MASV, TENSV, PHAI, NGAYSINH
HAVING AVG(DIEMLAN1) > 8

--BAI7
--Hiển thị thông tin sinh viên gồm: Mã SV, tên SV, GT, ngày sinh, Điểm TB kiểm tra
--lần1, chỉ hiển thị 5 người có điểm thấp nhất

SELECT TOP 5 A.MASV, TENSV, CASE PHAI WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI, NGAYSINH, AVG(DIEMLAN1) AS TBDIEMLAN1
FROM SINHVIEN A, DIEM B
WHERE A.MASV = B.MASV
GROUP BY A.MASV, TENSV, PHAI, NGAYSINH
ORDER BY TBDIEMLAN1 ASC

--BAI8
--Hiển thị những môn có số tỉn chỉ lớn hơn hoặc bằng số tin chỉ của môn TIUD

SELECT * FROM MONHOC
WHERE SOTC >= (SELECT SOTC FROM MONHOC WHERE MAMH LIKE N'TIUD')

--BAI9
--Hiển thị hai sinh viên nữ và hai sinh viên nam có điểm TB kiểm lần 1 cao nhất.

--CREATE VIEW
CREATE VIEW HAISVNU
AS
SELECT TOP 2 A.MASV, TENSV, CASE PHAI WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI, NGAYSINH, AVG(DIEMLAN1) AS TBDIEMLAN1
FROM SINHVIEN A, DIEM B
WHERE A.MASV = B.MASV AND PHAI = 0
GROUP BY A.MASV, TENSV, PHAI, NGAYSINH
ORDER BY TBDIEMLAN1 DESC

--CREATE VIEW
CREATE VIEW HAISVNAM
AS
SELECT TOP 2 A.MASV, TENSV, CASE PHAI WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI, NGAYSINH, AVG(DIEMLAN1) AS TBDIEMLAN1
FROM SINHVIEN A, DIEM B
WHERE A.MASV = B.MASV AND PHAI = 1
GROUP BY A.MASV, TENSV, PHAI, NGAYSINH
ORDER BY TBDIEMLAN1 DESC

--VIEW
SELECT * FROM HAISVNU
UNION
SELECT * FROM HAISVNAM

--BAI10

--BAI11
--Hiển thị thông tin sinh viên bổ sung cột tuổi.

SELECT *, DATEDIFF(YY,NGAYSINH, GETDATE()) AS TUOI FROM SINHVIEN

--BAI12
--Hiển thị sinh viên ở khoa Hệ thống thông tin. (có 3 ký tự cuối là HTT)

SELECT * FROM SINHVIEN WHERE MALOP LIKE N'%HTT'

--BAI13
--Hiển thị hai sinh viên đầu tiên có điểm cao nhất

SELECT TOP 2 A.MASV, TENSV, CASE PHAI WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI, NGAYSINH , (DIEMLAN1 + DIEMLAN2)/2 AS DIEM
FROM SINHVIEN A, DIEM B
ORDER BY DIEM DESC

--BAI14
--Thay đổi ràng buộc giữa bảng DIEM và SINHVIEN để có thể xóa được sinh viên đã có điểm 
-- sau đó xóa sinh viên có Mã là SV05.

ALTER TABLE SINHVIEN
ADD CONSTRAINT CHANGERANGBUOC UNIQUE (MASV) 

ALTER TABLE DIEM
--DROP CONSTRAINT FK__DIEM__MASV__3D5E1FD2
ADD CONSTRAINT FK__DIEM__MASV FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)

DELETE FROM SINHVIEN WHERE MASV LIKE 'SV05'

--BAI15
--Bổ sung vào cơ sở dữ liệu bảng GIANGVIEN và bảng GIANGDAY tạo ra các ràng
--buộc để có CSDL mới như như sau:

USE QLSinhVien
GO
CREATE TABLE GIANGDAY
(
	MAGV NVARCHAR(10) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	MALOP NVARCHAR(10) FOREIGN KEY REFERENCES LOP(MALOP),
	MAMH NVARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
	TGBD DATETIME,
	TGKT DATETIME
)

DROP TABLE GIAOVIEN

ALTER TABLE GIAOVIEN
DROP COLUMN MAKHOA

USE QLSinhVien
GO
CREATE TABLE GIAOVIEN
(
	MAGV NVARCHAR(10) NOT NULL PRIMARY KEY,
	TENGV NVARCHAR(50),
	GT BIT,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(50),
)

--BAI18
--Thực hiện tri vấn để in kết quả như sau MAGV, TENGV , TUOI ,PHAI

SELECT  MAGV, TENGV,DATEDIFF(YY, NGAYSINH, GETDATE()) AS TUOI, CASE GT WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI
FROM GIAOVIEN

--BAI19
--Lọc ra GV đến tuổi nghỉ hưu (Nam>=60, Nữ>=55)
SELECT  MAGV, TENGV,DATEDIFF(YY, NGAYSINH, GETDATE()) AS TUOI, CASE GT WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI
FROM GIAOVIEN
WHERE (GT = 1 AND DATEDIFF(YY, NGAYSINH, GETDATE()) >= 60) OR (GT = 0 AND DATEDIFF(YY, NGAYSINH, GETDATE()) >= 55)

--BAI20
--Hiển thị thông tin của một giáo viên nữ và một giáo viên nam có tuổi cao nhất

CREATE VIEW [NAMOLDESE]
AS
SELECT TOP 1  MAGV, TENGV,DATEDIFF(YY, NGAYSINH, GETDATE()) AS TUOI, CASE GT WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI
FROM GIAOVIEN
WHERE GT = 1
ORDER BY TUOI DESC

CREATE VIEW [NUOLDESE]
AS
SELECT TOP 1 MAGV, TENGV,DATEDIFF(YY, NGAYSINH, GETDATE()) AS TUOI, CASE GT WHEN 1 THEN 'NAM' ELSE 'NU' END AS PHAI
FROM GIAOVIEN
WHERE GT = 0
ORDER BY TUOI DESC

SELECT * FROM NAMOLDESE
UNION
SELECT * FROM NUOLDESE

--BAI21
--Thống kê số giờ dạy cho giảng viên. Không thống kê những lớp chưa kết thúc

SELECT DATEDIFF(HH, TGBD, TGKT) AS GIO
FROM GIANGDAY
WHERE TGKT IS NOT NULL

--BAI22
--Hiển thị những lớp chưa kết thúc với những thông tin sau TENGV, TENLOP, TENMH, TGBD, TGKT

SELECT TENGV, TENLOP, TENMH, TGBD, TGKT
FROM GIANGDAY A, LOP B, MONHOC C, GIAOVIEN D
WHERE A.MAGV = D.MAGV AND A.MALOP = B.MALOP AND A.MAMH = C.MAMH AND TGKT IS NULL

--BAI23
--Tính trung bình giờ dạy cho mỗi khoa. Ba ký tự đầu của mã GV là mã khoa: CNT là
--khoa công nghệ thông tin. DTV là khoa điện tử viễn thông

CREATE VIEW TBGIODAYGV 
AS
SELECT MAGV , AVG(DATEDIFF(HH, TGBD, TGKT)) AS DIEMTB
FROM GIANGDAY
WHERE TGKT IS NOT NULL
GROUP BY MAGV

SELECT SUBSTRING(A.MAGV,1,3) AS MAGV, AVG(DIEMTB)
FROM GIAOVIEN A, TBGIODAYGV B
WHERE A.MAGV = B.MAGV
GROUP BY SUBSTRING(A.MAGV,1,3)

--BAI24
-- Hiển thị những sinh viên chưa có điểm môn nào

SELECT * FROM SINHVIEN
WHERE MASV IN (SELECT MASV FROM DIEM WHERE DIEMLAN1 IS NULL OR DIEMLAN2 IS NULL)

--BAI25
--Hiển thị sinh viên học ít nhất 3 môn:
--Cơ sở dữ liệu, Cấu trúc dữ liệu và Toán rời rạc


--BAI26
--Hiển thị tất cả những môn đã dạy xong nhưng chưa có điểm
SELECT * FROM MONHOC
WHERE MAMH IN (SELECT MAMH FROM GIANGDAY WHERE TGKT IS NOT NULL) AND 
MAMH IN (SELECT MAMH FROM DIEM WHERE DIEMLAN1 IS NULL OR DIEMLAN2 IS NULL)

--BAI27
-- Hiển thị tên của những giáo viên đã dạy xong nhưng chưa nhập điểm

CREATE VIEW MAMH_MALOP_CHUACODIEM
AS
SELECT MAMH, MALOP
FROM DIEM, (SELECT MASV, MALOP FROM SINHVIEN) LOP
WHERE (DIEMLAN1 IS NULL OR DIEMLAN2 IS NULL) AND DIEM.MASV = LOP.MASV

SELECT * FROM GIAOVIEN
WHERE MAGV IN (SELECT MAGV FROM GIANGDAY A, MAMH_MALOP_CHUACODIEM B WHERE A.MALOP = B.MALOP AND A.MAMH = B.MAMH)

--BAI28
-- Cập nhật điểm thi lần 1 môn CSDL cho sinh viên SV01 lên 2 điểm

UPDATE DIEM
SET DIEMLAN1 += 2
WHERE MASV LIKE 'SV01'

--BAI29
--Cập nhật điểm thi lần 1 môn CTDL ho sinh viên lớp K19TPM lên 1

UPDATE DIEM
SET DIEMLAN1 += 1
WHERE MAMH LIKE 'CTDL' AND MASV IN (SELECT MASV FROM SINHVIEN WHERE MALOP LIKE 'K19TPM')

--BAI30
-- Xóa điểm của những sinh viên có điểm thi lần 1 nhỏ hơn 3

UPDATE DIEM
SET DIEMLAN1 = NULL, DIEMLAN2 = NULL
WHERE DIEMLAN1 < 3

